import * as tf from '@tensorflow/tfjs';
import { bundleResourceIO } from '@tensorflow/tfjs-react-native';
import * as FileSystem from 'expo-file-system';
import '@tensorflow/tfjs-backend-cpu';
import '@tensorflow/tfjs-backend-webgl';


const modelJsonPath = FileSystem.documentDirectory + 'model/model.json';
const modelWeights = [
  FileSystem.documentDirectory + 'model/group1-shard1of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard2of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard3of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard4of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard5of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard6of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard7of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard8of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard9of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard10of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard11of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard12of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard13of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard14of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard15of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard16of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard17of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard18of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard19of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard20of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard21of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard22of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard23of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard24of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard25of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard26of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard27of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard28of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard29of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard30of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard31of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard32of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard33of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard34of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard35of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard36of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard37of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard38of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard39of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard40of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard41of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard42of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard43of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard44of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard45of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard46of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard47of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard48of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard49of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard50of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard51of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard52of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard53of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard54of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard55of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard56of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard57of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard58of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard59of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard60of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard61of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard62of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard63of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard64of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard65of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard66of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard67of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard68of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard69of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard70of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard71of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard72of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard73of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard74of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard75of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard76of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard77of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard78of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard79of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard80of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard81of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard82of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard83of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard84of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard85of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard86of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard87of250.bin',
  FileSystem.documentDirectory + 'model/group1-shard88of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard89of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard90of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard91of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard92of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard93of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard94of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard95of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard96of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard97of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard98of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard99of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard100of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard101of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard102of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard103of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard105of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard106of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard107of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard108of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard109of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard110of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard111of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard112of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard113of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard114of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard115of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard116of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard117of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard118of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard119of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard120of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard121of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard122of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard123of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard124of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard125of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard126of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard127of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard128of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard129of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard130of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard131of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard132of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard133of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard134of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard135of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard136of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard137of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard138of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard139of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard140of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard141of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard142of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard143of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard144of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard145of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard146of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard147of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard148of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard149of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard150of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard151of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard152of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard153of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard154of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard155of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard156of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard157of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard158of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard159of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard160of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard161of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard162of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard163of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard164of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard165of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard166of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard167of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard168of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard169of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard170of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard171of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard172of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard173of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard174of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard175of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard176of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard177of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard178of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard179of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard180of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard181of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard182of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard183of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard184of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard185of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard186of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard187of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard188of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard189of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard190of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard191of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard192of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard193of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard194of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard195of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard196of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard197of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard198of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard199of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard200of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard201of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard202of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard203of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard204of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard205of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard206of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard207of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard208of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard209of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard210of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard211of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard212of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard213of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard214of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard215of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard216of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard217of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard218of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard219of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard220of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard221of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard222of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard223of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard224of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard225of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard226of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard227of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard228of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard229of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard230of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard231of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard232of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard233of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard234of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard235of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard236of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard237of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard238of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard239of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard240of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard241of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard242of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard243of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard244of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard245of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard246of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard247of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard248of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard249of250.bin',
   FileSystem.documentDirectory + 'model/group1-shard250of250.bin',
];

// Modeli yükleyip tahmin yapmak için fonksiyon
export const loadModelAndPredict = async () => {
  await tf.ready();  // TensorFlow ortamını başlat

  // WebGL backend yüklü mü kontrol ediyoruz
  if (tf.getBackend() !== 'webgl') {
    await tf.setBackend('webgl');  // Noktalı virgül ekledik
    console.log('WebGL backend yüklendi.');  // Noktalı virgül ekledik
  }

  try {
    // Modeli yükle
    const model = await tf.loadGraphModel(bundleResourceIO(modelJsonPath, modelWeights));  // Noktalı virgül ekledik
    console.log('Model başarıyla yüklendi.');  // Noktalı virgül ekledik

    // Dummy bir input tensor oluşturuyoruz (224x224 RGB resim)
    const inputTensor = tf.zeros([1, 224, 224, 3]);  // Noktalı virgül ekledik

    // Tahmin yap
    const prediction = model.predict(inputTensor);  // Noktalı virgül ekledik
    prediction.print();  // Noktalı virgül ekledik

    return prediction;  // Noktalı virgül ekledik

  } catch (error) {
    console.error('Model yüklenirken bir hata oluştu:', error);  // Noktalı virgül ekledik
    return null;  // Noktalı virgül ekledik
  }
};